#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define FLYWHEEL_MOTOR 17

#define RIGHT_FRONT_MOTOR 12
#define LEFT_FRONT_MOTOR 15
#define RIGHT_BACK_MOTOR 13
#define LEFT_BACK_MOTOR 11

#define FLYWHEEL_GEARSET pros::E_MOTOR_GEARSET_06
#define DRIVETRAIN_GEARSET pros::E_MOTOR_GEARSET_18

#define ENCODER_UNITS pros::E_MOTOR_ENCODER_DEGREES

#endif//CONSTANTS_HPP