/// Miscellaneous constant values, stored in this header for convenience

#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define FLYWHEEL_MOTOR 3
#define INTAKE_MOTOR 1
#define INDEXER_MOTOR 19
#define ROLLER_MOTOR 0
#define ROLLER_OPTICAL 18

#define RIGHT_FRONT_MOTOR 4
#define LEFT_FRONT_MOTOR 11
#define RIGHT_BACK_MOTOR 10
#define LEFT_BACK_MOTOR 20

#define FLYWHEEL_GEARSET pros::E_MOTOR_GEARSET_06
#define INTAKE_GEARSET pros::E_MOTOR_GEARSET_18
#define INDEXER_GEARSET pros::E_MOTOR_GEARSET_18
#define DRIVETRAIN_GEARSET pros::E_MOTOR_GEARSET_18

#define ENCODER_UNITS pros::E_MOTOR_ENCODER_DEGREES

#endif // CONSTANTS_HPP
