#ifndef VEXV5_CONSTANTS_HPP
#define VEXV5_CONSTANTS_HPP

#define RIGHT_FRONT_MOTOR 12
#define LEFT_FRONT_MOTOR 15
#define RIGHT_BACK_MOTOR 13
#define LEFT_BACK_MOTOR 11

#define DRIVETRAIN_GEARSET pros::E_MOTOR_GEARSET_18
#define ENCODER_UNITS pros::E_MOTOR_ENCODER_DEGREES


#endif//VEXV5_CONSTANTS_HPP