on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=MinSizeRel --toolchain toolchain.cmake -B build

      - name: Build with CMake
        run: cmake --build build/

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
