on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:39

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: dnf install -y arm-none-eabi-binutils-cs arm-none-eabi-gcc-cs arm-none-eabi-gcc-cs-c++ arm-none-eabi-newlib cmake ninja-build

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=MinSizeRel --toolchain toolchain-gcc.cmake -B build

      - name: Build with CMake
        run: cmake --build build/

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
