on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y gcc-arm-none-eabi llvm
      - uses: actions/cache@v3
        with:
          path: bin/
          key: ${{ runner.os }}-makefile-${{ hashFiles('Makefile', 'common.mk') }}
          restore-keys: |
            ${{ runner.os }}-makefile-
      - run: make
